// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXh0WuMMoY1L8up7Ec8qQCVa_Pnf2PdIU',
    appId: '1:206774427020:android:80e8dddf5b71d440d08aa9',
    messagingSenderId: '206774427020',
    projectId: 'rsrs-1dae6',
    databaseURL: 'https://rsrs-1dae6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rsrs-1dae6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDq-Dsx6QEvU1nsalCFGGRL0UwziCXBQ08',
    appId: '1:206774427020:ios:0dfc5f272e0323a4d08aa9',
    messagingSenderId: '206774427020',
    projectId: 'rsrs-1dae6',
    databaseURL: 'https://rsrs-1dae6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rsrs-1dae6.appspot.com',
    androidClientId: '206774427020-5d5gbjb8t3roi6nb4kr1frreehu2mtqt.apps.googleusercontent.com',
    iosClientId: '206774427020-jh505q8b9faek89amlfvjihkj3abugdc.apps.googleusercontent.com',
    iosBundleId: 'com.example.assignment',
  );
}
